version: "3.4"
services:
  web:
    image: "groove8/user-profile-server:latest"
    build: .
    user: "root"
    environment:
      DB_HOST: "mongo"
    ports:
      - "80:80"
    volumes:
      - ./backend/src/public/photos/:/home/node/app/public/photos
    depends_on:
      - mongo
  mongo:
    image: groove8/user-profile-db:latest
    build: ./db/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
      DB_NAME: app
      DB_USER: user-service
      DB_PASS: example
    volumes:
      - data:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  user-photos:
    name: user-photos
  data:
    name: mongodb-data