version: "3.4"
services:
  web:
    image: "groove8/user-profile-demo:server"
    user: "root"
    environment:
      DB_HOST: "mongo"
    ports:
      - "80:80"
    volumes:
      - user-photos:/home/node/app/public/photos
    depends_on:
      - mongo
  mongo:
    image: groove8/user-profile-demo:db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
      DB_NAME: app
      DB_USER: user-service
      DB_PASS: example
    volumes:
      - data:/data/db

volumes:
  user-photos:
    name: user-photos
  data:
    name: mongodb-data